name: suitmedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  get_it: ^8.0.3
  dio: ^5.1.0
  retrofit: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^9.7.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
